### ISSUE TITLE
Metamod doesn't seem to run w/ Windows 64bit srcds_x64.exe of Insurgency using DEV 1.11 MM-1105

### ISSUE THREAD

**Issue by Daimyo21** [alliedmodders/metamod-source#47]
So I opened an issue thread on sourcemod after the recent insurgency update (5-4-18) which is resolved after I got the 32bit srcds.exe working for DEV 1.11 MM-1105 and Sourcemod 1.10.0-git6275-windows.  

However now, anytime I run the same start command with the srcds_x64.exe, metamod and sourcemod don't load.  Is this something that can be fixed on metamod side or does NWI have to update the 64bit exe to make it compatible? 

I'd really like to take advantage of any 64bit performance gains so it would be nice if MM/SM ran with it.

**Comment by psychonic** [comment]
Firstly, you're unlikely to get any meaningful performance gains. The CS:GO ran some benchmarks across different platform and determined that it wasn't worth shipping a 64-bit version for Windows based on that, (only Linux and Mac). Insurgency's engine is very similar to CS:GO's under the hood.

MM:S is supported on 64-bit platforms in general, but we've not built or tested it on any Source 1 game on Windows. There's also an issue blocking us from shipping any Win64 auto-builds in our current setup  (See #40)

Beyond that, I don't recall the state of SM on 64-bit platforms. @TheDS was working on it, at least for Linux and Mac. I think it may have landed in the Dev branch. I don't remember if Win64 was looked at since there was only one Source 1 game that supported it, and it was another third-party title.
